package org.srr.dev.util;

public class EmojiUtils {

    public static String convertTag(String str) {
        return str
//                .replaceAll("<", "&lt;")
                .replaceAll(":mask:", "<img src=\"emoji_1\"/>")
                .replaceAll(":no_mouth:", "<img src=\"emoji_2\"/>")
                .replaceAll(":astonished:", "<img src=\"emoji_3\"/>")
                .replaceAll(":sleeping:", "<img src=\"emoji_4\"/>")
                .replaceAll(":flushed:", "<img src=\"emoji_5\"/>")
                .replaceAll(":astonished:", "<img src=\"emoji_6\"/>")
                .replaceAll(":scream:", "<img src=\"emoji_7\"/>")
                .replaceAll(":cold_sweat:", "<img src=\"emoji_8\"/>")
                .replaceAll(":anguished:", "<img src=\"emoji_9\"/>")
                .replaceAll(":open_mouth:", "<img src=\"emoji_10\"/>")
                .replaceAll(":sob:", "<img src=\"emoji_11\"/>")
                .replaceAll(":grimacing:", "<img src=\"emoji_12\"/>")
                .replaceAll(":weary:", "<img src=\"emoji_13\"/>")
                .replaceAll(":thumbsup:", "<img src=\"emoji_14\"/>")
                .replaceAll(":weary:", "<img src=\"emoji_15\"/>")
                .replaceAll(":fearful:", "<img src=\"emoji_16\"/>")
                .replaceAll(":anguished:", "<img src=\"emoji_17\"/>")
                .replaceAll(":frowning:", "<img src=\"emoji_18\"/>")
                .replaceAll(":disappointed_relieved:", "<img src=\"emoji_19\"/>")
                .replaceAll(":triumph:", "<img src=\"emoji_20\"/>")
                .replaceAll(":persevere:", "<img src=\"emoji_21\"/>")
                .replaceAll(":cry:", "<img src=\"emoji_22\"/>")
                .replaceAll(":rage:", "<img src=\"emoji_23\"/>")
                .replaceAll(":angry:", "<img src=\"emoji_24\"/>")
                .replaceAll(":worried:", "<img src=\"emoji_25\"/>")
                .replaceAll(":disappointed:", "<img src=\"emoji_26\"/>")
                .replaceAll(":stuck_out_tongue_closed_eyes:", "<img src=\"emoji_27\"/>")
                .replaceAll(":stuck_out_tongue_winking_eye:", "<img src=\"emoji_28\"/>")
                .replaceAll(":stuck_out_tongue:", "<img src=\"emoji_29\"/>")
                .replaceAll(":kissing_closed_eyes:", "<img src=\"emoji_30\"/>")
                .replaceAll(":kissing_smiling_eyes:", "<img src=\"emoji_31\"/>")
                .replaceAll(":kissing_heart:", "<img src=\"emoji_32\"/>")
                .replaceAll(":kissing:", "<img src=\"emoji_33\"/>")
                .replaceAll(":confounded:", "<img src=\"emoji_34\"/>")
                .replaceAll(":confused:", "<img src=\"emoji_35\"/>")
                .replaceAll(":pensive:", "<img src=\"emoji_36\"/>")
                .replaceAll(":sweat:", "<img src=\"emoji_37\"/>")
                .replaceAll(":unamused:", "<img src=\"emoji_38\"/>")
                .replaceAll(":expressionless:", "<img src=\"emoji_39\"/>")
                .replaceAll(":neutral_face:", "<img src=\"emoji_40\"/>")
                .replaceAll(":smirk:", "<img src=\"emoji_41\"/>")
                .replaceAll(":sunglasses:", "<img src=\"emoji_42\"/>")
                .replaceAll(":heart_eyes:", "<img src=\"emoji_43\"/>")
                .replaceAll(":relieved:", "<img src=\"emoji_44\"/>")
                .replaceAll(":yum:", "<img src=\"emoji_45\"/>")
                .replaceAll(":blush:", "<img src=\"emoji_46\"/>")
                .replaceAll(":wink:", "<img src=\"emoji_47\"/>")
                .replaceAll(":smiling_imp:", "<img src=\"emoji_48\"/>")
                .replaceAll(":innocent:", "<img src=\"emoji_49\"/>")
                .replaceAll(":laughing:", "<img src=\"emoji_50\"/>")
                .replaceAll(":sweat_smile:", "<img src=\"emoji_51\"/>")
                .replaceAll(":smile:", "<img src=\"emoji_52\"/>")
                .replaceAll(":smiley:", "<img src=\"emoji_53\"/>")
                .replaceAll(":joy:", "<img src=\"emoji_54\"/>")
                .replaceAll(":grin:", "<img src=\"emoji_55\"/>")
                .replaceAll(":grinning:", "<img src=\"emoji_56\"/>")
                .replaceAll(":clap:", "<img src=\"emoji_57\"/>")
                .replaceAll(":thumbsdown:", "<img src=\"emoji_58\"/>")
                .replaceAll(":sleepy:", "<img src=\"emoji_59\"/>")
                .replaceAll(":ok_hand:", "<img src=\"emoji_60\"/>")
                .replaceAll(":wave:", "<img src=\"emoji_61\"/>")
                .replaceAll(":facepunch:", "<img src=\"emoji_62\"/>")
                .replaceAll(":point_right:", "<img src=\"emoji_63\"/>")
                .replaceAll(":point_left:", "<img src=\"emoji_64\"/>")
                .replaceAll(":point_down:", "<img src=\"emoji_65\"/>")
                .replaceAll(":point_up_2:", "<img src=\"emoji_66\"/>")
                .replaceAll(":dog:", "<img src=\"emoji_67\"/>")
                .replaceAll(":heart:", "<img src=\"emoji_68\"/>")
                .replaceAll(":relaxed:", "<img src=\"emoji_69\"/>")
                .replaceAll(":v:", "<img src=\"emoji_70\"/>")
                .replaceAll(":raised_hand:", "<img src=\"emoji_71\"/>")
                .replaceAll(":fist:", "<img src=\"emoji_72\"/>")
//		.replaceAll("","<img src=\"e075\"/>")
                ;
    }

    public static String convertEmojiHtml(String str) {
        return str
                .replaceAll("&lt;", "<")
                .replaceAll("<img src=\"emoji_1\"/>", ":mask:")
                .replaceAll("<img src=\"emoji_2\"/>", ":no_mouth:")
                .replaceAll("<img src=\"emoji_3\"/>", ":astonished:")
                .replaceAll("<img src=\"emoji_4\"/>", ":sleeping:")
                .replaceAll("<img src=\"emoji_5\"/>",":flushed:")
                .replaceAll("<img src=\"emoji_6\"/>", ":astonished:")
                .replaceAll("<img src=\"emoji_7\"/>", ":scream:")
                .replaceAll("<img src=\"emoji_8\"/>", ":cold_sweat:")
                .replaceAll("<img src=\"emoji_9\"/>", ":anguished:")
                .replaceAll("<img src=\"emoji_10\"/>",":open_mouth:")
                .replaceAll("<img src=\"emoji_11\"/>", ":sob:")
                .replaceAll("<img src=\"emoji_12\"/>", ":grimacing:")
                .replaceAll("<img src=\"emoji_13\"/>", ":weary:")
                .replaceAll("<img src=\"emoji_14\"/>",":thumbsup:")
                .replaceAll("<img src=\"emoji_15\"/>", ":weary:")
                .replaceAll("<img src=\"emoji_16\"/>", ":fearful:")
                .replaceAll("<img src=\"emoji_17\"/>",":anguished:")
                .replaceAll("<img src=\"emoji_18\"/>", ":frowning:")
                .replaceAll("<img src=\"emoji_19\"/>", ":disappointed_relieved:")
                .replaceAll("<img src=\"emoji_20\"/>", ":triumph:")
                .replaceAll("<img src=\"emoji_21\"/>", ":persevere:")
                .replaceAll("<img src=\"emoji_22\"/>", ":cry:")
                .replaceAll("<img src=\"emoji_23\"/>",":rage:")
                .replaceAll("<img src=\"emoji_24\"/>",":angry:")
                .replaceAll("<img src=\"emoji_25\"/>",":worried:")
                .replaceAll("<img src=\"emoji_26\"/>",":disappointed:")
                .replaceAll("<img src=\"emoji_27\"/>",":stuck_out_tongue_closed_eyes:")
                .replaceAll("<img src=\"emoji_28\"/>",":stuck_out_tongue_winking_eye:")
                .replaceAll("<img src=\"emoji_29\"/>",":stuck_out_tongue:")
                .replaceAll("<img src=\"emoji_30\"/>",":kissing_closed_eyes:")
                .replaceAll("<img src=\"emoji_31\"/>",":kissing_smiling_eyes:")
                .replaceAll("<img src=\"emoji_32\"/>",":kissing_heart:")
                .replaceAll("<img src=\"emoji_33\"/>",":kissing:")
                .replaceAll("<img src=\"emoji_34\"/>",":confounded:")
                .replaceAll("<img src=\"emoji_35\"/>",":confused:")
                .replaceAll("<img src=\"emoji_36\"/>",":pensive:")
                .replaceAll("<img src=\"emoji_37\"/>",":sweat:")
                .replaceAll("<img src=\"emoji_38\"/>",":unamused:")
                .replaceAll("<img src=\"emoji_39\"/>",":expressionless:")
                .replaceAll("<img src=\"emoji_40\"/>",":neutral_face:")
                .replaceAll("<img src=\"emoji_41\"/>",":smirk:")
                .replaceAll("<img src=\"emoji_42\"/>",":sunglasses:")
                .replaceAll("<img src=\"emoji_43\"/>",":heart_eyes:")
                .replaceAll("<img src=\"emoji_44\"/>",":relieved:")
                .replaceAll("<img src=\"emoji_45\"/>",":yum:")
                .replaceAll("<img src=\"emoji_46\"/>",":blush:")
                .replaceAll("<img src=\"emoji_47\"/>",":wink:")
                .replaceAll("<img src=\"emoji_48\"/>",":smiling_imp:")
                .replaceAll("<img src=\"emoji_49\"/>",":innocent:")
                .replaceAll("<img src=\"emoji_50\"/>",":laughing:")
                .replaceAll("<img src=\"emoji_51\"/>",":sweat_smile:")
                .replaceAll("<img src=\"emoji_52\"/>",":smile:")
                .replaceAll("<img src=\"emoji_53\"/>",":smiley:")
                .replaceAll("<img src=\"emoji_54\"/>",":joy:")
                .replaceAll("<img src=\"emoji_55\"/>",":grin:")
                .replaceAll("<img src=\"emoji_56\"/>",":grinning:")
                .replaceAll("<img src=\"emoji_57\"/>",":clap:")
                .replaceAll("<img src=\"emoji_58\"/>",":thumbsdown:")
                .replaceAll("<img src=\"emoji_59\"/>", ":sleepy:")
                .replaceAll("<img src=\"emoji_60\"/>",":ok_hand:")
                .replaceAll("<img src=\"emoji_61\"/>",":wave:")
                .replaceAll("<img src=\"emoji_62\"/>",":facepunch:")
                .replaceAll("<img src=\"emoji_63\"/>",":point_right:")
                .replaceAll("<img src=\"emoji_64\"/>",":point_left:")
                .replaceAll("<img src=\"emoji_65\"/>",":point_down:")
                .replaceAll("<img src=\"emoji_66\"/>",":point_up_2:")
                .replaceAll("<img src=\"emoji_67\"/>", ":dog:")
                .replaceAll("<img src=\"emoji_68\"/>", ":heart:")
                .replaceAll("<img src=\"emoji_69\"/>", ":relaxed:")
                .replaceAll("<img src=\"emoji_70\"/>",":v:")
                .replaceAll("<img src=\"emoji_71\"/>",":raised_hand:")
                .replaceAll("<img src=\"emoji_72\"/>",":fist:")
                ;
    }

        public static String convertEmoji(String str) {
                return str
                        .replaceAll("emoji_001", ":mask:")
                        .replaceAll("emoji_002", ":no_mouth:")
                        .replaceAll("emoji_003", ":astonished:")
                        .replaceAll("emoji_004", ":sleeping:")
                        .replaceAll("emoji_005",":flushed:")
                        .replaceAll("emoji_006", ":astonished:")
                        .replaceAll("emoji_007", ":scream:")
                        .replaceAll("emoji_008", ":cold_sweat:")
                        .replaceAll("emoji_009", ":anguished:")
                        .replaceAll("emoji_010",":open_mouth:")
                        .replaceAll("emoji_011", ":sob:")
                        .replaceAll("emoji_012", ":grimacing:")
                        .replaceAll("emoji_013", ":weary:")
                        .replaceAll("emoji_014",":thumbsup:")
                        .replaceAll("emoji_015", ":weary:")
                        .replaceAll("emoji_016", ":fearful:")
                        .replaceAll("emoji_017",":anguished:")
                        .replaceAll("emoji_018", ":frowning:")
                        .replaceAll("emoji_019", ":disappointed_relieved:")
                        .replaceAll("emoji_020", ":triumph:")
                        .replaceAll("emoji_021", ":persevere:")
                        .replaceAll("emoji_022", ":cry:")
                        .replaceAll("emoji_023",":rage:")
                        .replaceAll("emoji_024",":angry:")
                        .replaceAll("emoji_025",":worried:")
                        .replaceAll("emoji_026",":disappointed:")
                        .replaceAll("emoji_027",":stuck_out_tongue_closed_eyes:")
                        .replaceAll("emoji_028",":stuck_out_tongue_winking_eye:")
                        .replaceAll("emoji_029",":stuck_out_tongue:")
                        .replaceAll("emoji_030",":kissing_closed_eyes:")
                        .replaceAll("emoji_031",":kissing_smiling_eyes:")
                        .replaceAll("emoji_032",":kissing_heart:")
                        .replaceAll("emoji_033",":kissing:")
                        .replaceAll("emoji_034",":confounded:")
                        .replaceAll("emoji_035",":confused:")
                        .replaceAll("emoji_036",":pensive:")
                        .replaceAll("emoji_037",":sweat:")
                        .replaceAll("emoji_038",":unamused:")
                        .replaceAll("emoji_039",":expressionless:")
                        .replaceAll("emoji_040",":neutral_face:")
                        .replaceAll("emoji_041",":smirk:")
                        .replaceAll("emoji_042",":sunglasses:")
                        .replaceAll("emoji_043",":heart_eyes:")
                        .replaceAll("emoji_044",":relieved:")
                        .replaceAll("emoji_045",":yum:")
                        .replaceAll("emoji_046",":blush:")
                        .replaceAll("emoji_047",":wink:")
                        .replaceAll("emoji_048",":smiling_imp:")
                        .replaceAll("emoji_049",":innocent:")
                        .replaceAll("emoji_050",":laughing:")
                        .replaceAll("emoji_051",":sweat_smile:")
                        .replaceAll("emoji_052",":smile:")
                        .replaceAll("emoji_053",":smiley:")
                        .replaceAll("emoji_054",":joy:")
                        .replaceAll("emoji_055",":grin:")
                        .replaceAll("emoji_056",":grinning:")
                        .replaceAll("emoji_057",":clap:")
                        .replaceAll("emoji_058",":thumbsdown:")
                        .replaceAll("emoji_059", ":sleepy:")
                        .replaceAll("emoji_060",":ok_hand:")
                        .replaceAll("emoji_061",":wave:")
                        .replaceAll("emoji_062",":facepunch:")
                        .replaceAll("emoji_063",":point_right:")
                        .replaceAll("emoji_064",":point_left:")
                        .replaceAll("emoji_065",":point_down:")
                        .replaceAll("emoji_066",":point_up_2:")
                        .replaceAll("emoji_067", ":dog:")
                        .replaceAll("emoji_068", ":heart:")
                        .replaceAll("emoji_069", ":relaxed:")
                        .replaceAll("emoji_070",":v:")
                        .replaceAll("emoji_071",":raised_hand:")
                        .replaceAll("emoji_072", ":fist:")
                        ;
        }
}